### ISSUE TITLE
Properly handling python_min variable for host requirements

### ISSUE THREAD

**Issue by matthewfeickert** [hadim/feedrattler#4]
👋 Hi. I was very happy to see in today's (2025-02-27) [Announcing the new recipe format on conda-forge](https://conda-forge.org/blog/2025/02/27/conda-forge-v1-recipe-support/) post that there's an automatic convert tool. Thank you very much for writing it!

I just converted https://github.com/conda-forge/pyhf-feedstock/ (in https://github.com/conda-forge/pyhf-feedstock/pull/31) and I was very impressed. However, there was one thing that I noticed that was different than I expected. In https://github.com/conda-forge/pyhf-feedstock/commit/87386f9a3a7ff1fbbc52f4229804609ec460b3e0 (I rebased the PR, so this commit isn't in there now) there is the `context` variable `python_min` but it (the variable) was not used for `requirements.host.python` but instead the value was replaced instead.

So the `recipe/meta.yml` was

```yaml
{% set python_min = "3.7" %}

...

requirements:
  host:
    - python {{ python_min }}
```

and it got converted in `recipe/recipe.yaml` to

```yaml
schema_version: 1

context:
...
  python_min: 3.7

...

requirements:
  host:
    - python 3.7.*
```

This also [raises a linter error](https://github.com/conda-forge/pyhf-feedstock/pull/31#issuecomment-2689390590).

This got correctly handled though for both the `run` requirements and the `test` requirements

```yaml
  run:
    - python >=${{ python_min }}

...

  - requirements:
      run:
        - python ${{ python_min }}.*
```

and so I ended up editing it to use in the final recipe (https://github.com/conda-forge/pyhf-feedstock/commit/0e634894cd1535f4d2af1f4e6163f7430b5a0f23)

```yaml
requirements:
  host:
    - python ${{ python_min }}.*
```

This seems like a bug, but there might be some subtle reason that I'm missing that this behavior happened.
